Update config.yml
ssm env

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,15 +1,56 @@
+
+version: 2
 jobs:
-  my-job:
+  aws-ecr/build_and_push_image:
     docker:
     - image: circleci/python:3-stretch-browsers
     steps:
-      - aws-parameter-store/load
-      - checkout
-orbs:
-  aws-parameter-store: circleci/aws-parameter-store@1.0.0
-version: 2.1
+    - run:
+        name: Install AWS CLI
+        command: |
+          if [[ $(command -v pip) == "" ]]; then
+            echo "PIP is required to install AWS CLI and is not available."
+            exit 1
+          else
+            if [[ $(command -v sudo) == "" ]]; then
+              echo "SUDO is required to install AWS CLI and is not available."
+              exit 1
+            else
+              if [[ $(command -v aws) == "" ]]; then
+                sudo pip install awscli
+              else
+                echo "AWS CLI is already installed."
+              fi
+            fi
+          fi
+    - run:
+        name: Configure cli credentials
+        command: |
+          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID --profile default
+          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY --profile default
+    - run:
+        name: Configure default region
+        command: |
+          aws configure set region us-east-1 --profile default
+    - checkout
+    - setup_remote_docker
+    - run:
+        name: Log into Amazon ECR
+        command: $(aws ecr get-login --no-include-email --region us-east-1 )
+    - run:
+        name: Build docker image
+        command: |
+          Id=$(aws ssm get-parameters --names Account_Number --with-decryption)
+          docker build -t $Id.dkr.ecr.us-east-1.amazonaws.com/dockertest:ssmenv .
+    - run:
+        name: Push image to Amazon ECR
+        command: docker push $Id.dkr.ecr.us-east-1.amazonaws.com/dockertest:ssmscan
+    - run: 
+        name: Image scanning in ECR 
+        command:  aws ecr start-image-scan --repository-name dockertest --image-id imageTag=circlciscaning --region us-east-1
+ 
 workflows:
-  build_and_test:
+  build-and-deploy:
     jobs:
-      - my-job
+    - aws-ecr/build_and_push_image
   version: 2
